appid := env('APPID')
install-dir := env('INSTALL_DIR')
desktop-src := appid + '.desktop'
desktop-dst := install-dir / 'applications' / desktop-src
metainfo-src := appid + '.metainfo.xml'
metainfo-dst := install-dir / 'metainfo' / metainfo-src
icon-src := appid + '.png'
icon-dst := install-dir / 'icons' / 'hicolor' / '512x512' / 'apps' / icon-src

install:
    install -Dm0644 {{ desktop-src }} {{ desktop-dst }}
    install -Dm0644 {{ metainfo-src }} {{ metainfo-dst }}
    install -Dm0644 {{ icon-src }} {{ icon-dst }}

uninstall:
    rm -r {{ desktop-dst }}
    rm -r {{ metainfo-dst }}
    rm -r {{ icon-dst }}
