#!/bin/bash

APPDIR="${APPDIR:-"$(cd "$(dirname "$0")" && pwd)"}"

export PATH="$APPDIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="$APPDIR/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export XDG_CONFIG_DIRS="$APPDIR/usr/etc/xdg${XDG_CONFIG_DIRS:+:$XDG_CONFIG_DIRS}"
export STARDUST_THEMES="$APPDIR/usr/share"

exec telescope "$@"
