#!/usr/bin/env bash

if ! [[ -z $WAYLAND_DISPLAY ]]; then
export FLAT_WAYLAND_DISPLAY=$WAYLAND_DISPLAY
fi

export WAYLAND_DISPLAY=$(display-socket-finder wayland)
stardust-xr-wayland-service -p "${APPDIR:-}/usr/libexec/telescope_default_panel_shell" $WAYLAND_DISPLAY &

export DISPLAY=$(display-socket-finder x11)
sleep 0.5 && xwayland-satellite $DISPLAY &

gravity -- 0 0.0 -0.5 hexagon_launcher &
black-hole &

WAYLAND_DISPLAY=$FLAT_WAYLAND_DISPLAY manifold | simular &
