#!/bin/bash

stardust-xr-wayland-service wayland-32 &
export WAYLAND_DISPLAY=wayland-32

xwayland-satellite :10 &
export DISPLAY=:10

flatland &
gravity -- 0 0.0 -0.5 hexagon_launcher &
black-hole &

WAYLAND_DISPLAY=$FLAT_WAYLAND_DISPLAY manifold | simular &
